// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIXProjectPackageString = "914991fa-a485-4975-bcae-e9c28bcc82b1";
        public static Guid guidVSIXProjectPackage = new Guid(guidVSIXProjectPackageString);

        public const string guidVSIXProjectPackageCmdSetString = "ae9d8dfd-f729-41d0-9b8b-9a1f1f63a012";
        public static Guid guidVSIXProjectPackageCmdSet = new Guid(guidVSIXProjectPackageCmdSetString);

        public const string guidImagesString = "509dd6ff-e0d0-4d2f-8fd3-dbdde0d66245";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidVSIXProjectPackageCmdSet1String = "5a5af03f-dd37-49f4-80a9-91babac628d3";
        public static Guid guidVSIXProjectPackageCmdSet1 = new Guid(guidVSIXProjectPackageCmdSet1String);

        public const string guidImages1String = "f3dd19b9-e741-4293-8235-6ae3bfaf3120";
        public static Guid guidImages1 = new Guid(guidImages1String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
        public const int cmdidInsertGuidCommand = 0x0100;
        //public const int MyMenuGroup = 0x1020;
        //public const int bmpPic1 = 0x0001;
        //public const int bmpPic2 = 0x0002;
        //public const int bmpPicSearch = 0x0003;
        //public const int bmpPicX = 0x0004;
        //public const int bmpPicArrows = 0x0005;
        //public const int bmpPicStrikethrough = 0x0006;
    }
}